version: '3.9'
networks:
  spring-cloud-network:
    driver: bridge
services:     
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./configuration-data/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - 3000:3000
    volumes:
      - "./grafana-data:/var/lib/grafana"
    depends_on:
      - prometheus
  registry-server:
    container_name: registry-server
    build:
      context: service-registry-server
      dockerfile: Dockerfile
    image: service-registry-server:latest
    ports:
      - 58010:58010
    networks:
      - spring-cloud-network
    volumes:
      - "./logs:/logs"
    healthcheck:
      test: "curl --fail --silent localhost:58010/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  configuration-server:
    container_name: configuration-server
    build:
      context: configuration-server
      dockerfile: Dockerfile
    image: configuration-server
    ports:
      - 58020:58020
    networks:
      - spring-cloud-network
    volumes:
      - "./logs:/logs"
      - "./configuration-data:/configuration-data"
    environment:
      - EUREKA_SERVER=http://registry-server:58010/eureka
    depends_on:
      - registry-server
    healthcheck:
      test: "curl --fail --silent localhost:58020/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  gateway-server:
    container_name: gateway-server
    build:
      context: gateway-server
      dockerfile: Dockerfile
    image: gateway-server
    ports:
      - 58000:58000
    networks:
      - spring-cloud-network
    volumes:
      - "./logs:/logs"
    environment:
      - EUREKA_SERVER=http://registry-server:58010/eureka
      - CONFIG_SERVER=http://configuration-server:58020/
      - KEYSTORE_PATH=/bin/keystore.p12
      - PORT_NUMBER=58112
    depends_on:
      - configuration-server
    healthcheck:
      test: "curl --fail --silent localhost:58000/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: on-failure
  common-service:
    container_name: common-service
    build:
      context: common-service
      dockerfile: Dockerfile
      args:
        - PORT_NUMBER=58111
    image: common-service
    ports:
      - 58111:58111
    networks:
      - spring-cloud-network
    volumes:
      - "./logs:/logs"
    environment:
      - EUREKA_SERVER=http://registry-server:58010/eureka
      - CONFIG_SERVER=http://configuration-server:58020/
      - PORT_NUMBER=58111
    depends_on:
      - gateway-server
    healthcheck:
      test: "curl --fail --silent localhost:58111/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: on-failure
  common-service-2:
    container_name: common-service-2
    build:
      context: common-service
      dockerfile: Dockerfile
      args:
        - PORT_NUMBER=58111
    image: common-service
    ports:
      - 58112:58112
    networks:
      - spring-cloud-network
    volumes:
      - "./logs:/logs"
    environment:
      - EUREKA_SERVER=http://registry-server:58010/eureka
      - CONFIG_SERVER=http://configuration-server:58020/
      - PORT_NUMBER=58112
    depends_on:
      - gateway-server
    healthcheck:
      test: "curl --fail --silent localhost:58112/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: on-failure