server:
  port: 58010
spring:
  application:
    name: service-registry-server
  cloud:
    config:
      enabled: false
logging:
  file:
    path: ../logs/${spring.application.name}/${server.port}
    max-size: 10MB
    max-history: 30
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF
      jefflks: INFO
    org:
      springframework: INFO