server:
  port: 58000
  ssl:
    key-store-type: PKCS12
    key-store: 'file:${KEYSTORE_PATH:keystore.p12}'
    key-store-password: JeffLKS@123
    key-alias: jefflks
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:58010/eureka/
    healthcheck:
      enabled: true
logging:
  file:
    path: ../logs/${spring.application.name}/${server.port}
    max-size: 10MB
    max-history: 30
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
  level:
    com:
      netflix:
        discovery: false
        eureka: false
      jefflks: INFO
    org:
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
spring:
  cloud:
    gateway:
      routes:
      - id: common-client
        uri: lb://common-client/
        predicates:
        - Path=/common/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true