server:
  port: 58000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:58010/eureka/}
    healthcheck:
      enabled: true
logging:
  file:
    path: ../logs/${spring.application.name}/${server.port}
    max-size: 10MB
    max-history: 30
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
  level:
    com:
      netflix:
        discovery: false
        eureka: false
      jefflks: INFO
    org:
      springframework: INFO
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
  endpoint:
    info:
      enabled: true
spring:
  application:
    apiId: test
    apiKey: testing123
    apiSubscription: 
  cloud:
    gateway:
      routes:
      - id: common-service
        uri: lb://common-service/
        predicates:
        - Path=/common-service/**
        filters:
        - name: CircuitBreaker
          args:
            name: commonServiceCircuitBreaker
            fallbackuri: forward:/fallback/CommonService
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true