global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'gateway-server'
    scrape_interval: 5s
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:58000']
        labels:
          application: 'gateway-server'
    tls_config:
      insecure_skip_verify: true